# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0002_auto_20170203_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryplugin',
            name='display_type',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('teaser', 'Teaser')], max_length=256),
        ),
    ]
