# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0003_auto_20190120_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='gallery', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
